practice_app/apps/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
]

practice_app/apps/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.index ,name="user-home"),
    path('user-list/', views.userList,name="user-list"),
    path('user-detail/', views.userDetail ,name="user-detail"),
    path('user-detail-worker', views.userDetailWorker, name="user-detail-worker"),
    path('user-create/', views.userCreate ,name="user-create"),
    path('user-create-worker', views.userCreateWorker, name="user-create-worker"),
    path('api-overview/', views.apiOverview, name="api-overview"),
    path('api-user-list/', views.userListApi, name="api-user-list"),
    path('api-user-detail/<str:pk>', views.userDetailApi, name="api-user-detail"),
    path('api-user-create/', views.userCreateApi, name="api-user-create"),
]

practice_app/practice_app/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Practice Application Advice App API Documentation",
      description="API documentation for the Advice App endpoint of the practice application.",
      default_version=""
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
   authentication_classes=[],
   patterns=[path('advice/', include('apps.advice.urls'))],
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('report/',include ('apps.report.urls')),
    path('', include('apps.home.urls')),
    path('location_mgr/', include('apps.location_mgr.urls')),
    path('advice/', include('apps.advice.urls')),
    path('article/', include('apps.article.urls')),
    path('news/', include('apps.news.urls')),
    path('user/', include('apps.user.urls')),
    path('post/', include('apps.post.urls')),
    path('coronavirus/', include('apps.coronavirus.urls')),
    path('drug-side-effects/', include('apps.drug_side_effects.urls')),
    path('comment/', include('apps.comment.urls')),
    path('hospital/', include('apps.hospital.urls')),
    path('advicedocs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]

practice_app/apps/user/models.py
from django.db import models

class User(models.Model):
    horoscope_choices = [
        ("aries","Aries"), 
        ("taurus","Taurus"), 
        ("gemini","Gemini"), 
        ("cancer","Cancer"), 
        ("leo","Leo"), 
        ("virgo","Virgo"), 
        ("libra","Libra"), 
        ("scorpio","Scorpio"), 
        ("sagittarius","Sagittarius"), 
        ("capricorn","Capricorn"), 
        ("aquarius","Aquarius"),
        ("pisces","Pisces")
    ]
    username = models.CharField(max_length=50, unique = True)
    password = models.CharField(max_length=50)
    mail = models.EmailField(max_length = 254, unique = True)
    horoscope = models.CharField(max_length=11,choices=horoscope_choices, default="aries")

    def __str__(self):
        return self.username

practice_app/apps/user/forms.py
from django import forms

horoscope_choices = [
        ("aries","Aries"), 
        ("taurus","Taurus"), 
        ("gemini","Gemini"), 
        ("cancer","Cancer"), 
        ("leo","Leo"), 
        ("virgo","Virgo"), 
        ("libra","Libra"), 
        ("scorpio","Scorpio"), 
        ("sagittarius","Sagittarius"), 
        ("capricorn","Capricorn"), 
        ("aquarius","Aquarius"),
        ("pisces","Pisces")
    ]

class UserForm(forms.Form):
    username=forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password'}))
    mail=forms.EmailField(widget=forms.TextInput(attrs={'placeholder':'Email'}))
    horoscope=forms.CharField(widget=forms.Select(choices= horoscope_choices, attrs={'placeholder':'Horoscope'}))

practice_app/apps/home/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.renderers import TemplateHTMLRenderer
from django.http import JsonResponse
from django.http import HttpRequest

class Index(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'home.html'

    def get(self, req):
        return Response({})

practice_app/apps/user/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from rest_framework.decorators import api_view
from rest_framework.response import Response
import json
from .serializers import UserSerializer
from .models import User
from .forms import UserForm
import requests
from rest_framework import status

def index(request):
    return render(request, 'user-home.html')

@api_view(['GET'])
def userList(request):
    users = User.objects.all()
    serializer = UserSerializer(users, many=True)
    data = serializer.data
    users=[]
    for row in data:
        id = row["id"]
        username = row["username"]
        password = row["password"]
        mail= row["mail"]
        horoscope = row["horoscope"]
        users.append((id, username, password, mail,horoscope))

    return render(request,'user-list.html',{"results": users})

def userDetail(request):
    return render(request,'user-detail.html')

@api_view(['GET','POST'])
def userDetailWorker(request):
    username=request.POST["username"]

    try:
        user = User.objects.get(username=username)
        serializer = UserSerializer(user, many=False)
        data = serializer.data
    
        users=[]
        id = data["id"]
        username = data["username"]
        password = data["password"]
        mail= data["mail"]
        horoscope = data["horoscope"]

        params = (
        ('sign', horoscope),
        ('day', 'today'),
        )
        
        daily = requests.post('https://aztro.sameerkumar.website/', params=params)
        resp = daily.json()

        desc = resp["description"] 

        users.append((id, username, password, mail,horoscope))   
        return render(request,'user-detail.html',{"results": users, "daily":desc})

    except:
        isFailed=request.GET.get("fail",True)
        return render(request,'user-detail.html',{"action_fail": isFailed}, status=status.HTTP_404_NOT_FOUND)

def userCreate(request):
    form = UserForm()
    isFailed=request.GET.get("fail",False)
    isSuccessful=request.GET.get("success",False)
    return render(request,'user-create.html',{"action_success": isSuccessful, "action_fail": isFailed,"form":form})

@api_view(['POST'])
def userCreateWorker(request):
    form = UserForm()
    serializer = UserSerializer(data = request.data)

    if serializer.is_valid():
        serializer.save()
        isFailed=request.GET.get("fail",False)
        isSuccessful=request.GET.get("success",True)
        return render(request, 'user-create.html',{"action_success": isSuccessful,"action_fail": isFailed,"form":form})
    else:
        isFailed=request.GET.get("fail",True)
        isSuccessful=request.GET.get("success",False)
        return render(request, 'user-create.html',{"action_success": isSuccessful,"action_fail": isFailed,"form":form},status=status.HTTP_422_UNPROCESSABLE_ENTITY)

@api_view(['GET'])
def apiOverview(request):
    api_urls = {
        'List':'/user-list/',
        'Detail':'/user-detail/',
        'Post':'/user-create/',
    }
    return Response(api_urls)

@api_view(['GET'])
def userListApi(request):
    users = User.objects.all()
    serializer = UserSerializer(users, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def userDetailApi(request, pk):
    user = User.objects.get(id=pk)
    serializer = UserSerializer(user, many=False)
    return Response(serializer.data)

@api_view(['POST'])
def userCreateApi(request):
    serializer = UserSerializer(data=request.data)

    if serializer.is_valid():
        serializer.save()

    return Response(serializer.data)

practice_app/apps/user/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  	<title>Home</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
	
</head>
<body>
	<div class="wrapper">
        <div style="background-color:#ADD8E6; !important" class="jumbotron text-center bg-primary">
            <h1> User Portal </h1>
            <p>
				Welcome!
            </p>
        </div>
	</div>
	<div class="container">
		<div class="row">
			<div class="d-flex justify-content-around" style="margin-top: 20px">    
                <a class="btn btn-primary" href="user-list">List All Users</a>
			</div>
			<div class="d-flex justify-content-around" style="margin-top: 20px">  
                <a class="btn btn-primary" href="user-detail">List a User</a>
			</div>
			<div class="d-flex justify-content-around" style="margin-top: 20px">  
                <a class="btn btn-primary" href="user-create">Add a User</a>	         
			</div>
		</div>
	</div>
</body>
</html>

practice_app/apps/user/templates/user-create.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  	<title>User Create</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
	<div class="wrapper">
        <div style="background-color:#FF8D6E; !important" class="jumbotron text-center bg-primary">
            <h1> User Portal </h1>
            <p>
				Welcome!
            </p>
        </div>
	</div>
	<div class="container">
		{% if action_success %}
            <div class="alert alert-success" role="alert">
                <h4 class="alert-heading">Successful</h4>
                <p>User is added successfully.</p>
            </div>
        {% endif %}
		{% if action_fail %}
            <div class="alert alert-danger" role="alert">
                <h4 class="alert-heading">Failed</h4>
                <p>Username or e-mail address is not valid.</p>
            </div>
        {% endif %}
		<div class="container-fluid">
			<div class="center">
				<form class="form-group" method="POST" novalidate action="{% url 'user:user-create-worker' %}">
					{{form|crispy}}
					{% csrf_token %}
					<button type="submit" style="margin-top: 10px;"class="btn btn-success">Add</button>
				</form>
			</div>
		</div>
	</div>
	<a href="{%url 'user:user-home' %}"> <p style="text-align:center">Back to Home Page</p></a>
</body>
</html>

practice_app/apps/user/templates/user-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  	<title>User Detail</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

	<style type="text/css">
		table {
			font-family: arial, sans-serif;
			border-collapse: collapse;
			width: 100%;
			}
		td, th {
			border: 1px solid #dddddd;
			text-align: left;
			padding: 8px;
			}
		tr:nth-child(even) {
			background-color: #dddddd;
			}

	</style>
</head>
<body>
	<div class="wrapper">
        <div style="background-color: #FF8D6E; !important" class="jumbotron text-center bg-primary">
            <h1> User Portal </h1>
            <p>
				Welcome!
            </p>
        </div>
	</div>
	<div class="container">
        <div class="container-fluid">
            {% if action_fail %}
            <div class="alert alert-danger" role="alert">
                <h4 class="alert-heading">Failed</h4>
                <p>Username is not valid.</p>
            </div>
            {% endif %}
            <div class="container">
                <table class="center">
                    <colgroup>
                        <col span="1" style="width: 10%;">
                        <col span="1" style="width: 30%;">
                        <col span="1" style="width: 30%;">
                        <col span="1" style="width: 30%;">
                        <col span="1" style="width: 30%;">
                    </colgroup>
                    <tr>
                        <th>ID</th>
                        <th>Username</th>
                        <th>Password</th>
                        <th>E-mail</th>
                        <th>Horoscope</th>
                    </tr>
                    {% for row in results %}
                    <tr>
                        {% for value in row %}
                        <td>
                            {{value}}
                        </td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </table>
                </div>
            </div>
            <div class="container">
                <div class="center">
                    <form id="postform" class="form-group" method="POST" action="{%url 'user:user-detail-worker' %}">
                            {% csrf_token %}
                            <br>
                            <label>Get User Detail:</label>
                            <br>
                            <input type="text" name="username" placeholder="Username" required>
                            <br>
                            <button type="submit" style="margin-top: 10px;"class="btn btn-success">Get</button>
                            <br>
                    </form>
                </div>
            </div>
            {% if daily %}
            <div class="alert alert-info" role="alert">
                <h4 class="alert-heading">Daily Horoscope</h4>
                <p>{{daily}}</p>
            </div>
            {% endif %}
        </div>
	</div>
    <a href="{%url 'user:user-home' %}"> <p style="text-align:center">Back to Home Page</p></a>
</body>
</html>

practice_app/apps/user/templates/user-home.html
<!DOCTYPE html>
<html lang="en">
<head>
  	<title>Home</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
	
</head>
<body>
	<div class="wrapper">
        <div style="background-color:#FF8D6E; !important" class="jumbotron text-center bg-primary">
            <h1> User Portal </h1>
            <p>
				Welcome!
            </p>
        </div>
	</div>
	<div class="container">
		<div class="row">
			<div class="d-flex justify-content-around" style="margin-top: 20px">    
                <a class="btn btn-success" href="user-list">List All Users</a>
			</div>
			<div class="d-flex justify-content-around" style="margin-top: 20px">  
                <a class="btn btn-success" href="user-detail">List a User</a>
			</div>
			<div class="d-flex justify-content-around" style="margin-top: 20px">  
                <a class="btn btn-success" href="user-create">Add a User</a>	         
			</div>
		</div>
		<a href="/" class="btn btn-secondary" role="button">Back to API List</a> <br>
	</div>
</body>
</html>

practice_app/apps/user/templates/user-list.html
<!DOCTYPE html>
<html lang="en">
<head>
  	<title>User List</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

	<style type="text/css">
		table {
			font-family: arial, sans-serif;
			border-collapse: collapse;
			width: 100%;
			}
		td, th {
			border: 1px solid #dddddd;
			text-align: left;
			padding: 8px;
			}
		tr:nth-child(even) {
			background-color: #dddddd;
			}

	</style>
</head>
<body>
	<div class="wrapper">
        <div style="background-color:#FF8D6E; !important" class="jumbotron text-center bg-primary">
            <h1> User Portal </h1>
            <p>
				Welcome!
            </p>
        </div>
	</div>
	<div class="container">
		<div class="container-fluid">
            <div class="container">
                <table class="center">
                   <colgroup>
						<col span="1" style="width: 10%;">
						<col span="1" style="width: 30%;">
						<col span="1" style="width: 30%;">
						<col span="1" style="width: 30%;">
						<col span="1" style="width: 30%;">
                	</colgroup>
                    <tr>
						<th>ID</th>
                        <th>Username</th>
                        <th>Password</th>
                        <th>E-mail</th>
						<th>Horoscope</th>
                    </tr>
                    {% for row in results %}
                    <tr>
                        {% for value in row %}
                        <td>
                            {{value}}
                        </td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                    </table>
                </div>
			</div>
		</div>
	</div>
    <a href="{%url 'user:user-home' %}"> <p style="text-align:center">Back to Home Page</p></a>
</body>
</html>